### ISSUE TITLE
Why usrsctp_sendv cannot send data after trasmitting data for a period of time

### ISSUE THREAD

**Issue by starwarfan** [sctplab/usrsctp#122]
I wrote a program to transmit data refer to the ekr_peer, with non_bloking set to true. The peers keep sending and receiving data once connection established. The data transmission is fine at the begining, but after about half an hour, the send call fails and the errno is EWOULDBLOCK.
After turned on the SCTP_DEBUG flag, I found that the "USR send complete qo:0" message changed to "qo:1" when the data trasmission became blocked, and never back to "qo:0".  The "queue_only" variable is set to 1 because of the
((net->flight_size > net->cwnd) && (stcb->asoc.sctp_cmt_on_off == 0)) condition is true.
Is there any restrict to send data, and what will cause this?

**Comment by tuexen** [comment]
Are you using an up to date of usrsctp? If not, please update, since I fixed a bug which could cause the behaviour you are describing in https://github.com/sctplab/usrsctp/commit/00657acb1338ac01a6dc242900f09102305d9a60. You should be able to transfer data. If the problem also exists when using the current source, are you able to provide the program to reproduce the issue?

**Comment by starwarfan** [comment]
After updating usrsctp, the issue cannot be reproduced so far. The connection is fine after hours now. Thank you for solving my problem.
