### ISSUE TITLE
usrsctp send buffer does not clear itself

### ISSUE THREAD

**Issue by PowerInside** [sctplab/usrsctp#143]
We're working on a webRTC data channels library that uses usrsctp, but in our test application, we keep hitting the default send buffer (256kB) and it doesn't seem like it's clearing on its own. Is there a specific flag or an attribute that we could be missing out in the implementation or is this a bug?

Related: https://github.com/chadnickbok/librtcdcpp/issues/28

**Comment by tuexen** [comment]
I'm not aware of any issues related to this. Using the test programs I can transfer 100 MB. Running the server using `programs/tsctp -E 9899` and running the client `programs/tsctp -E 9999 -U 9899 -n 100000  127.0.0.1`.

**Comment by PowerInside** [comment]
I guess that program works well. Here's the pcapng file anyway: https://ufile.io/btfvt

**Comment by tuexen** [comment]
I'll have a look at the file. Currently downloading...

**Comment by tuexen** [comment]
I can't see any problem in the tracefile. Is it a tracefile captured when you had a problem with your application? That is what I would need...

**Comment by zinovya** [comment]
Hi Michael, 

  I had a brief look into tracefile as well and I believe I can see there a number of issues related to a_rwnd calculation on side with port 5001:

1. It seems to me that endpoint with port 5001 calculates a_rwnd incorrectly. If you have a look at frame #21 and #25 you can see two SACK chunks. First acknowledges TSN 182463615, second - 182463617. That means that TSNs 182463616 and 182463617 arrived, both data chunk had length of 1024 bytes. In case when both chunks got buffered a_rwnd should decreased by 1024*2 bytes, shouldn't it? In trace file reported a_rwnd got decreased by 2560 bytes.

2. Endpoint with port 5001 had abruptly shrunk a_rwnd several times. You can find all occurrences of such behaviour by this filter (sctp.sack_a_rwnd==1).  The behaviour is seen in frames #38606 and #38607. SCTP just reported a_rwnd of 23552 bytes and cumulative TSN 182489167. Next SACK reports a_rwnd as 1 byte (which is strange enough by it self) and cumulative TSN as 182489169. As in example above TSNs 182489168 and 182489169 were 1024 bytes, so a_rwnd should be decreased by 2048 bytes, not by 23551. I think such behaviour can confuse sender, not sure if it will lead to EWOULDBLOCK.

3. There is also seems to be an issue with the way GAPs are handled by the same endpoint (port 5001). As far as I can see all of the DATA chunks are sent via stream #0  in order (I have not seen any chunk with ordered delivery bit set to 1), which means that if any DATA chunks got lost, TSNs received after that cannot be delivery to upper layer until missed chunks are re-transmitted (correct me if I'm wrong). If frames #3049, #3051 you can see SACK chunks that reported TSN 182465567 as last received in sequence. SACK from #3049 also reports that it received TSN 182465579 and decreased a_rwnd, which means that this TSN has been buffered. Next SACK at #3051 reports that cumulative TSN is still 182465567 and TSNs 182465579-182465580 are received as well. Since tsn 182465580 should have been buffered as well, that should lead to smaller value of a_rwnd reported in SACK chunk, however this didn't happen. A_rwnd reported in SACK #3049 and #3051 are the same - 131072 bytes. 

P.S. I don't know what SCTP implementation was used on the side with port 5001, maybe it was not usrsctp, but I just decided to let you know that there are some suspicious places in the trace file.

**Comment by PowerInside** [comment]
Thank you all for looking into this and sorry for the late response.

@tuexen, I thought you wanted me to run those two examples. I'll attach another trace once I figure out how to make the webRTC library talk to the sctp client/server. (I'll need to dismantle the DTLS layer)

Also, I have a feeling the SACK responses are not being redirected to the SCTP layer from DTLS layer after a while. I have a feeling there's a race condition in my implementation and it may not be the usrsctp library after all. I'll keep you all updated.

**Comment by zinovya** [comment]
If SACKs are been filtered out by DTLS we would see a lot of retransmissions in your tracefile, which I didn't see (there are some, but not a lot) and it is quite likely would to ungraceful association termination, which I didn't see either. That makes me think that SCTP on your end were receiving SACKs.

**Comment by PowerInside** [comment]
@zinovya the trace file above was just between two example tsctp programs bundled in usrsctp library. I thought @tuexen wanted me to do that first.

**Comment by tuexen** [comment]
@zinovya There is a known issue with the a_rwnd. See https://github.com/sctplab/usrsctp/issues/137. However, when the stack receives n bytes payload it has to buffer, it should decrement its a_rwnd by n + o, where o is some overhead. However, this is not working right now. I'll fix it soon.
`usrsctp` was used at both sides.
@PowerInside I wanted to see a tracefile showing the problem it figure out if you are also running in this problem. If you have some logging facility, you can integrate some logging of sent and received SCTP packets before/after DTLS handling without changing DTLS using `usrsctp_dumppacket()`. See [ekr_loop](https://github.com/sctplab/usrsctp/blob/master/programs/ekr_loop.c) for an example how it is used.

**Comment by PowerInside** [comment]
Here's the log file where I enabled `usrsctp_dumppacket()` before and after DTLS handling: https://drive.google.com/a/hamon.in/file/d/0B8arEHFxidkpTUVvcFktV0ZMZk0/view?usp=sharing

From line 32, you can notice that the `usrsctp_conninput()` function does not return for some reason. Line 24 and 26 seem to be the last call that worked.
