### ISSUE TITLE
Unable to change some sysctl variables with usrsctp_sysctl_set_*

### ISSUE THREAD

**Issue by ftsui** [sctplab/usrsctp#227]
For example hashtblsize and pcbtblsize are used in usrsctp_init, but usrsctp_init also calls sctp_init_sysctls() which resets all the variables to default values.

A possible fix would be to allow caller to call:
sctp_init_sysctls();
usrsctp_sysctl_set_XXX();

before calling usrsctp_init().
And prevent multiple invocation of sctp_init_sysctls, so that changes made before usrsctp_init() are preserved.

If this sounds reasonable, I can upload a patch.

**Comment by tuexen** [comment]
Isn't is being used in `sctp_inpcb_alloc()`? So you should be able to change the values after calling `sctp_init()` or am I missing something?

**Comment by tuexen** [comment]
Right. So you are referring to
```
TUNABLE_INT_FETCH("net.inet.sctp.tcbhashsize", &SCTP_BASE_SYSCTL(sctp_hashtblsize));
TUNABLE_INT_FETCH("net.inet.sctp.pcbhashsize", &SCTP_BASE_SYSCTL(sctp_pcbtblsize));
TUNABLE_INT_FETCH("net.inet.sctp.chunkscale", &SCTP_BASE_SYSCTL(sctp_chunkscale));
```
which are system tunables in FreeBSD. One could add a way to provide these three values in an additional functions and then, if they are set, use them. That would mimic the handling in the FreeBSD kernel. However, I think only the first one is relevant for the userland stack. So one could add a function which sets this value. Do you have a need for it? Do you think this is worth doing?

**Comment by ftsui** [comment]
Sorry, my write up might be a bit too confusing.

The issue I'm referring to are these line:
```
	SCTP_BASE_INFO(sctp_asochash) = SCTP_HASH_INIT((SCTP_BASE_SYSCTL(sctp_hashtblsize) * 31),
						       &SCTP_BASE_INFO(hashasocmark));
	SCTP_BASE_INFO(sctp_ephash) = SCTP_HASH_INIT(SCTP_BASE_SYSCTL(sctp_hashtblsize),
						     &SCTP_BASE_INFO(hashmark));
	SCTP_BASE_INFO(sctp_tcpephash) = SCTP_HASH_INIT(SCTP_BASE_SYSCTL(sctp_hashtblsize),
							&SCTP_BASE_INFO(hashtcpmark));
	SCTP_BASE_INFO(hashtblsize) = SCTP_BASE_SYSCTL(sctp_hashtblsize);
```
And other where SCTP_BASE_SYSCTL(sctp_hashtblsize) and others are used to init the hashtables.

For context, we are trying to use this for a severely constrained system, and we would like to reduce the sctp_hashtblsize and sctp_pcbtblsize to reduce memory footprint.  But doing something like:
```
usrsctp_init(...);
usrsctp_sysctl_set_sctp_hashtblsize(N);
usrsctp_sysctl_set_sctp_pcbtblsize(N);
```
does not work since the sizes are snapshotted in the lines above within usrsctp_init().   And switching the code to do:
```
usrsctp_sysctl_set_sctp_hashtblsize(N);
usrsctp_sysctl_set_sctp_pcbtblsize(N);
usrsctp_init(...);
```
doesn't work either since usrsctp_init() calls sctp_init_sysctls() internally and resets all the values to default.

Thus the idea of allowing caller to do:
```
sctp_init_sysctls();
usrsctp_sysctl_set_sctp_hashtblsize(N);
usrsctp_sysctl_set_sctp_pcbtblsize(N);
usrsctp_init(...);
```
And preventing the second call of sctp_init_sysctls() from overwritting the values set by caller.

**Comment by szatmz** [comment]
> sctp_init_sysctls();
> usrsctp_sysctl_set_sctp_hashtblsize(N);
> usrsctp_sysctl_set_sctp_pcbtblsize(N);
> usrsctp_init(...);

That would require sctp_init_sysctls be conditionally called inside usrsctp_init. We probably can't just remove the call there because that would break existing behavior. The condition would be 'has sctp_init_sysctls been already called?'. That could be checked through a global flag, but that flag would just take the memory and not used for majority of time and use cases. My thinking was that system_base_info as a global is initialized by the universal zero initializer (http://en.cppreference.com/w/c/language/struct_initialization). That already provides sufficient information if sctp_init_sysctls has been called or not yet, without taking up extra memory. 

An implementation in sctp_sysctl.c could look like this:

```
#define SET_NUMERIC_SCTP_BASE_SYSCTL(__m, value)  \
	do {                                                                                      \
		if (SCTP_BASE_SYSCTL(__m) == 0) {                      \
			SCTP_BASE_SYSCTL(__m) = (value);              \
		}                                                                                   \
	} while(0)
```

Then later replacing these two lines:
```
	SCTP_BASE_SYSCTL(sctp_hashtblsize) = SCTPCTL_TCBHASHSIZE_DEFAULT;
	SCTP_BASE_SYSCTL(sctp_pcbtblsize) = SCTPCTL_PCBHASHSIZE_DEFAULT;

```
with the above macro.

As for any concern of assumptions about types of values, that is the reason why I call the macro SET_NUMERIC_SCTP_BASE_SYSCTL instead of SET_SCTP_BASE_SYSCTL. That macro is supposed to be used for sysctls that are of numeric type and hence can be initialized to 0.

Thoughts?

**Comment by iffyb** [comment]
Hi, Tüxen! Sorry to overwhelm you, but we are concerned about diverging from the upstream too much, so were really hoping to get direction from you on how best to proceed.

Just to refresh: The problem we are trying to solve is to be able to programmatically manage allocations during init for our extremely constrained system.

Thanks!

**Comment by tuexen** [comment]
OK. Let me think about this. I think there is also a problem in FreeBSD. I'm contemplating that it is better to handle the sys tunables in a different way than the sysctls. Will provide feedback beginning next week and will come up with a patch.

**Comment by szatmz** [comment]
We are happy to upstream our above solution if you approve that.

**Comment by tuexen** [comment]
I understand... However, let me try to figure out if we also have a problem in FreeBSDs kernel implementation...

**Comment by tuexen** [comment]
I have added in https://github.com/sctplab/usrsctp/commit/48a387358b63c9709267bb16acbb41920effc45d a way to set sys tunables. You can now do
```
usrsctp_tunable_set_sctp_hashtblsize(N);
usrsctp_tunable_set_sctp_pcbtblsize(N);
usrsctp_tunable_set_sctp_chunkscale(N);
usrsctp_init(...);
```
I removed the functions

- `usrsctp_sysctl_set_sctp_hashtblsize()`
- `usrsctp_sysctl_set_sctp_pcbtblsize()`
- `usrsctp_sysctl_set_chunkscale()`

since they have never worked as expected. You can still use

- `usrsctp_sysctl_get_sctp_hashtblsize()`
- `usrsctp_sysctl_get_sctp_pcbtblsize()`
- `usrsctp_sysctl_get_chunkscale()`

to query the values after `sctp_init()` has been called. I think this fixes this issue. If not, or you have any further questions or comments, please reopen this issue.

**Comment by iffyb** [comment]
Wow, thanks, Tüxen! I am pretty sure this effectively solves our problem for those variables.

Unfortunately, we did just notice a couple other variables that pre-allocate some more memory that we would also like to tune down:
```
sctp_nr_outgoing_streams_default
sctp_nr_incoming_streams_default
```
in `usrsctplib/netinet/sctp_sysctl.c`.

This is all we know about for now, but I wonder if it suggests if we need a more general solution. e.g. either making `usrsctp_init_sysctls()` idempotent with a global bool, or make the same change for all the variables in `usrsctp_init_sysctls()`.

What do you think?

**Comment by tuexen** [comment]
These are normal sysctl variable and you should be able to change the defaults **before** creating end-points. Once you have created an end-point, but before the association has been initiated, you can change these values using the `SCTP_INITMSG ` socket option described in [Socket API](https://tools.ietf.org/html/rfc6458#section-8.1.3). Once the association has been established, you can only increase the number of streams using the extension defined in [RFC6525](https://tools.ietf.org/html/rfc6525), but this isn't used in WebRTC (assuming you are working on WebRTC).
