### ISSUE TITLE
Compatibility with FreeBSD

### ISSUE THREAD

**Issue by dlanie** [sctplab/usrsctp#281]
Hello,
I'm trying to setup usrsctp on a FreeBSD 11.2-Release system. However, when I run the echo_server and client from the example programs, the server always answers the INIT-Chunk with an ABORT.  
Type: 6, 
Chunk flags: 0x00
Zero error causes

I've tested this locally on a pc and on a local network, using the example programs as well as using my own programs. All combinations of these yielded the same result. 

Are there any additional configuration steps needed to fix this behaviour or is this maybe a compatibility problem with FreeBSD?

**Comment by weinrank** [comment]
You probably get an ABORT chunk because your (client) application talks to the FreeBSD kernel stack.
The kernel has no listening SCTP server and will respond with an ABORT.

If you're using the userland stack on a platform with native SCTP support, you should use UDP encapsulation to avoid this problem.

From the `echo_server` docs:
```
/*
 * Usage: echo_server [local_encaps_port] [remote_encaps_port]
 *
 * Example
 * Server: $ ./echo_server 11111 22222
 * Client: $ ./client 127.0.0.1 7 0 22222 11111
 */
```

As an alternative, you can recompile the FreeBSD kernel without native SCTP support.

**Comment by dlanie** [comment]
That worked, thanks
