### ISSUE TITLE
SCTP ordered message delivery

### ISSUE THREAD

**Issue by JlnWntr** [sctplab/usrsctp#290]
Is it possible to force *SCTP* to send all data completely ordered?

Let's do this experiment: 

1.  Take this [SCTP-discard-server][1] and this [SCTP-client][2].

2.  Let the client count to 100 a lot of times and send a byte each time respectively to the server.
 ```C
for(long i=0; i< 1000000000; i++){
	char temp = (char)(i%100) + 1;
	usrsctp_sendv(
		sock, (void *)&temp, 1,
		NULL, 0, NULL, 0, SCTP_SENDV_NOINFO, 0
	);
}
```
3. Let the server count along the same way and compare its number with the received one.
```C
printf("%d %d\n", (int)buffer[0], (int)(test));
if ((int)test != (int)buffer[0]) break;
```
Some seconds later: 
```bash
    66 66
    67 67
    68 68
    69 69
    51 70
```
I compiled this with `$ gcc discard_server.c -Wall -lusrsctp` using *gcc7.3.0* on my *Ubuntu 18.04* machine. 

What did I miss? Thanks in advance for any hint.

  [1]: https://github.com/sctplab/usrsctp/blob/master/programs/discard_server.c
  [2]: https://github.com/sctplab/usrsctp/blob/master/programs/client.c

**Comment by tuexen** [comment]
Sending all message completely ordered within each stream is the default and should work. I guess, what happens, is that the `usrsctp_sendv()` call fails (returns -1 and `errno` is set to `EWOULDBLOCK`) if the socket buffer is full. Since you don't check the return value and assume every `usrsctp_sendv()` call succeeds, it looks like the SCTP layer looses messages. But I guess it is the application which fails to provide all user messages until they are accepted by the SCTP layer. Can you check, if this explains the behaviour you are observing?

**Comment by JlnWntr** [comment]
Yes, this is the explanation! Thank you very much for that.

**Comment by nxrighthere** [comment]
@tuexen It's possible to increase the buffer size to minimize such failures?

**Comment by tuexen** [comment]
Yes, you can set the socket send buffer size. See [ekr_loop.c:403](https://github.com/sctplab/usrsctp/blob/master/programs/ekr_loop.c#L403).
