### ISSUE TITLE
stream reset and data sending

### ISSUE THREAD

**Issue by shiretu** [sctplab/usrsctp#31]
Suppose we have an SCTP ongoing between 2 peers: A and B.
A opens a stream S
B gets informed about the new stream and S is created on its side

Suppose A wants to send a large buffer. For this explanation, we consider this a large buffer:
`abcdefghijklmnopqrtsovw`

A will call `usrsctp_sendv(...)` with all necessary parameters, and the library takes that buffer and enqueues it for sending. The actual sending may or may not occur right away. Suppose is not happening right away, and the large buffer (or parts of it), gets enqueued inside the library.

At this point, if A resets the stream by doing `usrsctp_setsockopt(..., SCTP_RESET_STREAMS, ...)`, the internal queue is not discarded. That would not be a problem if the control messages are sent AFTER the data itself, but the control messages are taking priority and they will be sent first. 

Now, B will get the stream reset event immediately followed by data. The correct behavior should be one of this:
1. get the stream reset event and the in-transit data will be lost and never received. This requires A to completely erase the associated buffers BEFORE sending the reset event
2. get the data as it was queued up and than get the reset event

**Comment by tuexen** [comment]
I behaviour should be that A sends all messages on the outgoing stream, which is marked to be reset. Once all of these messages are acknowledged by the peer, the stream reconfiguration message gets sent. So B would get the data first, and then the stream reset event.

If you are not seeing the above described behaviour with the current sources it is a bug. Please let me know how to reproduce the problem.

There was a bug in the library such that the above was not happening but the event was delivered before the data or even the association broke. However, this was fixed in July.

**Comment by shiretu** [comment]
I think I have solved the problem, By respecting the RFC advice: only send `SCTP_STREAM_RESET_OUTGOING`

I was initially doing it like chrome does it. Look at line 919 here:
https://android.googlesource.com/platform/external/chromium_org/third_party/libjingle/source/talk/+/android-m-preview/media/sctp/sctpdataengine.cc

The code looks like this:
`resetp->srs_flags = SCTP_STREAM_RESET_INCOMING | SCTP_STREAM_RESET_OUTGOING;`

**Comment by tuexen** [comment]
I agree, the specification talks only about resetting outgoing streams (intentionally).

Best regards
Michael

**Comment by tuexen** [comment]
Doesn't seem to be an issue with usrsctp.
