### ISSUE TITLE
receive_cb not called when sending 256 kB

### ISSUE THREAD

**Issue by shampson** [sctplab/usrsctp#345]
We're trying to roll in the latest usrsctp into webrtc, and it is causing regressions in a PeerConnection unit test. I did a bisect and found the commit that causes the failure: https://github.com/sctplab/usrsctp/commit/be8e0ebaed64508599086f5c5795e13dace9e308

What's happening is the data comes in chunks via the callback (see logs below), but we never get a callback for the final chunk. This callback (hooked up via receive_cb) code is [here](https://cs.chromium.org/chromium/src/third_party/webrtc/media/sctp/sctp_transport.cc?type=cs&q=webrtc/media/sctp/sctp_transport.cc&g=0&l=271).

The test being run is [PeerConnectionEndToEndTest.CreateDataChannelLargeTransfer](https://cs.chromium.org/chromium/src/third_party/webrtc/pc/peer_connection_end_to_end_unittest.cc?l=538).

I added the custom logs (see my [change](https://webrtc-review.googlesource.com/c/src/+/148620)). Here's the files which includes just the relevant parts:
1.  [logs_before_commit.txt](https://github.com/sctplab/usrsctp/files/3483532/logs_before_commit.txt)
2. **Broken** [logs_after_commit.txt](https://github.com/sctplab/usrsctp/files/3483534/logs_after_commit.txt)

The test that is breaking is a pretty specific case. It is only when **sending exactly 256 kB** (1 less byte is fine). The other peculiar part is that it is only with a data channel created by the caller (PeerConnection that begins signaling) sending to its remote data channel. I made changes to the test and found that the other 3 possibilities (remote --> caller created, callee created --> remote, & remote --> callee created) do not fail.

I'm hoping that someone who is familiar with the library can quickly identify what caused this regression and we can make a fix. Thank you for your help.

**Comment by shampson** [comment]
@lgrahl Maybe you know who is best to look into this. Thanks!

**Comment by lgrahl** [comment]
Can you provide a pcap file of the SCTP packets for both cases (broken and working)?

**Comment by shampson** [comment]
Yup!

https://drive.google.com/drive/folders/1bzcKv9uwMYPh5qEkufKyrodMOY1TjOIV?usp=sharing

**Comment by shampson** [comment]
Has anybody given this a look? This is part of a merge requirement for chromium.

**Comment by tuexen** [comment]
> Has anybody given this a look? This is part of a merge requirement for chromium.

I looked at the .pcap files. They look strange... It seems that every packet is included at least twice, but with different IP addresses... So what stack are you using? I seems that you provide faked lower layers. Please just provide the SCTP packets, preferable with direction information. The `usrsctp_dumppacket()` provides everything you need to process with `text2pacp` to generate a .pcapng file without faked headers.

Are you able to reproduce the problem with a simple test program? I can try to play a bit with a `tsctp` tomorrow to see if I can recreate the problem.

**Comment by shampson** [comment]
The test I noted in the issue is the most simple repro I've made so far. I was able to debug the issue in wire shark with fake wrapped UDP headers and found that the very last DATA packet sent is missing the EOR bit being set. Before the culprit commit (success pcap) this bit is set. Is there an API change or reason that this isn't getting set? 

Here are the raw SCTP pcaps:
- [broken.pcapng](https://drive.google.com/open?id=1DSH911khL4-cs2NdL6s8vORvzBf9NgdV)
- [success.pcapng](https://drive.google.com/open?id=1w9vqi2L_Rz8sqDxnM5jSv46LLPCBzsZd)

In the drive folder I added the corresponding UDP fake header wrapped dumps as well.

Thanks a lot for looking into this @tuexen I appreciate it!

**Comment by tuexen** [comment]
@shampson I assume you log the SCTP packets using `usrsctp_dumppacket()`. Is that correct?
If that is correct, assume the logging output is in a text file with name `file.log`. Then do
```
grep SCTP_PACKET file.log > sctp.log
```
to generate a text file which contains only the textual description of the SCTP packets. To convert this to a `.pcapng` file, run
```
text2pcap -n -l 248 -D -t '%H:%M:%S.' sctp.log sctp.pcapng
```
The file `sctp.pcapng` should be readable by wireshark, contain the direction information, and all packets are detected as SCTP packets without further action. There are also no faked headers.
`text2pcap` is delivered with wireshark.

Can you provide `.pcapng` files, which are generated using the above commands?

**Comment by shampson** [comment]
@tuexen yes this is how I am generating the logs and filtering them. Looks like my text2pcap command was missing the -l 248 flag to specify the link layer header type:
```bash
text2pcap -t "%H:%M:%S." -D -n filtered_broken.log broken.pcapng
```

Success, adding this flag worked! Thank you!

Here are the updated pcapng files:

- before culprit commit: [success_sctp.pcapng](https://drive.google.com/open?id=1FupMVDxtO5cePHRKw-nFxOFhBOrG6ZyZ)
- after culprit commit, which is missing EOR in last DATA packet: [broken_sctp.pcapng](https://drive.google.com/open?id=1yUXffU0w48XkBkfFwcpkAeksvAxFjB98)

**Note**, the reason you are seeing duplicate inbound and outbound packets is because this is a test that connects two PeerConnections locally, so it is logging both inbound & outbound in the same test. 

It's the last outbound DATA packet that you can see is missing the EOR bit. We depend on this bit as of this change from about a year ago:
https://webrtc-review.googlesource.com/c/src/+/88900

**Comment by tuexen** [comment]
@shampson OK. The tracefiles are very good now. Thanks for updating them.

Both tracesfiles show 223 DATA chunks carrying 1172 bytes of payload each. This makes 260184 bytes. The last transmitted DATA chunk in the good case carries 788 bytes of payload (and the last fragment marker), which results in 260972 bytes of payload. How does this relate to your statement of sending a user message of 256 kB?

The bad tracefile shows that the last transmitted DATA chunk only carries 787 bytes (one byte less than in the good case). So if you are sending in both cases a user message of the same size it seems OK the the last fragment marker is missing, since there is one byte missing.

So the question is why is there a byte missing?

I have two questions:

* What is the length in bytes of the user message you are sending?
* Are you calling usrsctp_sendv() once for a user message or are you using the explicit EOR mode and are calling it multiple times?

**Comment by tuexen** [comment]
@shampson Since you nailed down the problem to https://github.com/sctplab/usrsctp/commit/be8e0ebaed64508599086f5c5795e13dace9e308, could you test with a version which includes all changes from that commit **except** the changes in `sctp_output.c`? I would expect that the test case works in this case based on looking at the changes...

My current guess is that the problem is related to the change in `sctp_output.c`, which replaces:
```
if (non_blocking) {
        /* we already checked for non-blocking above. */		
        max_len = sndlen;
} else {	
        max_len = SCTP_SB_LIMIT_SND(so) - inqueue_bytes;		
}
```
by
```
max_len = SCTP_SB_LIMIT_SND(so) - inqueue_bytes;
```
but I'm not sure. So it would be great if you could figure out if that is true or not...

**Comment by shampson** [comment]
@tuexen to answer your question, we are calling it once for a user message of size 256 * 1024 (done [here](https://cs.chromium.org/chromium/src/third_party/webrtc/media/sctp/sctp_transport.cc?l=559).

Thanks a lot for investigating this Michael! I tested without the changes to to `sctp_output.c` and you are correct, is what causes the problem.

**Comment by tuexen** [comment]
Can you also apply the changes to `sctp_output.c`, but change back the setting of `max_len` to the old version. In other words: Am I right that the problem is caused by the change I highlighted above?

**Comment by shampson** [comment]
I don't follow, what old version are you referring to for the changing the setting of `max_len`?

I think the change you highlighted above is the culprit, given that when I remove this change the culprit commit now passes the test.

**Comment by tuexen** [comment]
OK. Thanks for the clarification. Will try to figure out why this is going wrong.

**Comment by shampson** [comment]
@tuexen Thank you! 

To clarify these are the results of running the test with culprit commit https://github.com/sctplab/usrsctp/commit/be8e0ebaed64508599086f5c5795e13dace9e308:

- Normal case: **Failure**
- `sctp_output.c` reverted one commit back: **Pass**
- Remove `sctp_output.c`  `max_len` highlighted change : **Pass**

So yes, it looks like the `max_len` change is the culprit for that missing byte.

**Comment by tuexen** [comment]
@shampson OK. Thanks for the clarification. I tried to reproduce the issue locally but was not successful. I would like to understand what is going wrong instead of just reverting the change.

Would it be possible for you to run the test with additional debug output and provide that?

**Comment by shampson** [comment]
@tuexen Yes, are you referring to debug output from the sctp lib when running the test?

**Comment by tuexen** [comment]
@shampson I'm referring to that and to potentially additional output I would provide a patch for... If that is possible, it would be a great help. I'll try to bring up a patch with additional output, just this week being very busy with my day job...

**Comment by shampson** [comment]
Okay, here are the logs from the isolated test case:
- [sctp_lib_debug_broken.log](https://drive.google.com/open?id=1AkEpSo9yidLhhaxRp0evtDg7sN6mBGfL)
  - one commit behind the culprit commit
- [sctp_lib_debug_success.log](https://drive.google.com/open?id=1r6VBu741JqebNW1IzY6FW66PtqAx0KDp)
  - same commit, but incorporating the breaking `max_len` change in `sctp_output.c`

Let me know about the patch with additional output. Thanks again for looking into this!

**Comment by benjwright** [comment]
Hi tuexen, I have added a minimal pull request to address the issue. I traced back the issue into FreeBSD and I am a little concerned about going with this fix given that this issue was originally intended to address a fuzzing issue.

I think the best next steps here are to understand why this change in max_length was added in the first place and whether we need more safeguards around its calculation to prevent overflow etc.

**Comment by tuexen** [comment]
@shampson Aren't you using the explicit EOR mode? I think you enable it in [sctp_transport.cc:752](https://cs.chromium.org/chromium/src/third_party/webrtc/media/sctp/sctp_transport.cc?type=cs&q=webrtc/media/sctp/sctp_transport.cc&g=0&l=752). If that is true, then you don't check the return value of `usrsctp_sendv()` whether the whole message has been accepted by the SCTP stack or not in [sctp_transport.cc: 559](https://cs.chromium.org/chromium/src/third_party/webrtc/media/sctp/sctp_transport.cc?type=cs&q=webrtc/media/sctp/sctp_transport.cc&g=0&l=559).

So here is what I think is happening based on the debug output you provided (thanks a lot for that):

- Your send buffer size is 256 * 1024 = 262144.
- You send the ACK message of the data channel establishment protocol, which has a length of 1 byte. This is sent and buffered for potential retransmissions.
- You send a user message of 262144 bytes. Since there is only space for 262144 - 1 byte, the whole message doesn't fit. Since you enabled the explicit MSG_EOR mode, `usrsctp_sendv()` calls are not atomic anymore and the SCTP stack accepts what it can accept, which is 262143. I assume that this is the value returned by by `usrsctp_sendv()`. You should be able to verify that by adding debug output for that. Since the SCTP hasn't accepted all bytes, it assumes that the application will call again `usrsctp_sendv()` with the last byte and the `MSG_EOR` flag set.

So the SCTP stack did what it is told to do. The problem is in the application telling the stack one thing (requesting non-atomic `usrsctp_sendv()` calls) but is behaving differently (assuming `usrsctp_sendv()` calls).

Why does it show up after my change? Before my change the SCTP stack was not honouring the socket buffer size for non-blocking sockets just accepting the whole message. So the `usrsctp_sendv()` calls where actually atomic for non-blocking sockets even if they should not.
The fuzz tester was providing extremely large messages (which were accepted) and drove the kernel into an out of memory situation. This was fixed by actually honouring the send buffer limit, but resulting in the fact the `usrsctp_sendv()` are actually non-atomic when allowed. This what the bug in the application code is not hidden anymore.

To fix this, you need to decide whether you want to use non-atomic `usrsctp_sendv()` calls or not.
What do you want? Based on that, I can provide some hints how to fix the code in `sctp_transport.cc`.

**Comment by lgrahl** [comment]
Jeroen de Borst enabled explicit EOR mode on the way to https://bugs.chromium.org/p/webrtc/issues/detail?id=7774, probably due to confusing `MSG_EOR` with the explicit EOR mode when sending.

**Comment by shampson** [comment]
@lgrahl what bottom two changes can be reverted? Do you mean remove setting the explicit EOR mode for `usrsctp_sendv()` as well as `usrsctp_setsockopt()`?

This is my understanding, please correct me if I'm wrong. There are 3 places EOR was introduced in that [change](https://webrtc-review.googlesource.com/c/src/+/88900) from Jeroen.
1. **MSG_EOR**: Checking EOR on the receive side in order to to coalesce messages and get one callback from one send() call at the webrtc API level.
2. **SCTP_EXPLICIT_EOR**: Setting EOR explicitly as a socket option, meaning we need to explicitly set this on or off when sending messages.
3. **SCTP_EOR**: Set as a send flag with `usrsctp_sendv`

Sounds like we can remove #2 & #3, and still check for the EOR set on the receive side (#1) to coalesce? This would mean sending is now atomic and it would return -1 and block when trying to send in the same scenario? I can incorporate these changes and test tomorrow.

**Comment by tuexen** [comment]
@lgrahl You are right.
@shampson You have to distinguish the send path and the receive path. One the receive path you have always to check for MSG_EOR since partial delivery can almost always happen. You have no choice here. On the send path you do have a choice. The default is that send calls are atomic which limits the maximum user message size to the size of the send buffer. To overcome this limitation, you can enable the explicit EOR mode, which you do by calling the the `SCTP_EXPLICIT_EOR` socket option. Then you must set explicitly the SCTP_EOR flag when sending,  and the send calls are not atomic anymore.

I hope this clarifies things...

**Comment by lgrahl** [comment]
@shampson Yes. However, that being said, considering that you use the default buffer size of 256 KiB and the user application sends messages of size 256 KiB, I'd assume atomic sends would be detrimental to throughput since you constantly jump between buffer completely dry and buffer completely full. Please, correct me if I'm wrong on this, @tuexen.

**Comment by stewrtrs** [comment]
Thats not strictly true.

Consider an app  that

1) sends 256k
2) ack’s arrive that open the window (this should give a wakeup say at 128k ack'd)
3) The app then try’s to send the next 256k, but the return is only
     going to give you what was available i.e. 128k which means that this record
     is not completely sent you must restart at 128k in.
4) More acks arrive (again lets say another 128k) which should cause
5) The app to retry its last 1/2 of the message.


Now I am not familiar with the user stack and your options, I know in kernel land
you can set your “wakeup when I have send-space” what is termed lo_water to
some value.. the default is 1 byte… 

If I set it to 256k then what you say is true, you would not be awoken until
you had a full message space available… but one would hope you would not do
that so you could keep the buffer relatively full :)

R



> On Aug 22, 2019, at 5:00 AM, Lennart Grahl <notifications@github.com> wrote:
> 
> @shampson Yes. However, that being said, considering that you use the default buffer size of 256 KiB and the user application sends messages of size 256 KiB, I'd assume atomic sends would be detrimental to throughput since you constantly jump between buffer completely dry and buffer completely full. Please, correct me if I'm wrong on this, @tuexen.
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or mute the thread.
> 

------
Randall Stewart
rrs@netflix.com

**Comment by tuexen** [comment]
> Thats not strictly true. Consider an app that 1) sends 256k 2) ack’s arrive that open the window (this should give a wakeup say at 128k ack'd) 3) The app then try’s to send the next 256k, but the return is only going to give you what was available i.e. 128k which means that this record is not completely sent you must restart at 128k in.

That is only true if the user has enabled the explicit EOR mode. Only in that case `send()` calls are not atomic.

So I think @lgrahl is referring to the case where the explicit EOR mode is disabled and therefore
suggests to enable it. Then it will work as you describe.

> 4) More acks arrive (again lets say another 128k) which should cause 5) The app to retry its last 1/2 of the message. Now I am not familiar with the user stack and your options, I know in kernel land you can set your “wakeup when I have send-space” what is termed lo_water to some value.. the default is 1 byte… If I set it to 256k then what you say is true, you would not be awoken until you had a full message space available… but one would hope you would not do that so you could keep the buffer relatively full :) R
> […](#)

**Comment by stewrtrs** [comment]
Ahh I thought from the discussion we were talking about EOR mode on..

R

> On Aug 22, 2019, at 11:45 AM, Michael Tüxen <notifications@github.com> wrote:
> 
> Thats not strictly true. Consider an app that 1) sends 256k 2) ack’s arrive that open the window (this should give a wakeup say at 128k ack'd) 3) The app then try’s to send the next 256k, but the return is only going to give you what was available i.e. 128k which means that this record is not completely sent you must restart at 128k in.
> 
> That is only true if the user has enabled the explicit EOR mode. Only in that case send() calls are not atomic.
> 
> So I think @lgrahl is referring to the case where the explicit EOR mode is disabled and therefore
> suggests to enable it. Then it will work as you describe.
> 
> 	• More acks arrive (again lets say another 128k) which should cause 5) The app to retry its last 1/2 of the message. Now I am not familiar with the user stack and your options, I know in kernel land you can set your “wakeup when I have send-space” what is termed lo_water to some value.. the default is 1 byte… If I set it to 256k then what you say is true, you would not be awoken until you had a full message space available… but one would hope you would not do that so you could keep the buffer relatively full :) R
> …
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub, or mute the thread.
> 

------
Randall Stewart
rrs@netflix.com

**Comment by tuexen** [comment]
> Ahh I thought from the discussion we were talking about EOR mode on.. R
> […](#)

The problem is that Chrome enables the explicit EOR mode with a socket option, but does not handle non-atomic `send` calls...

**Comment by shampson** [comment]
@tuexen yes I understand, and thank you for the clarification. Handling the EOR on the receive side is fine, but send side needs to change.

We have 2 options.
1. Atomic send- remove explicitly setting the EOR bit when sending. I tried this and it immediately fixed the issue. The downside, as called out, is that this means waiting for a completely empty buffer before sending a message of the max size.
2. Explicitly set the EOR bit when sending.  We can partially buffer what wasn't sent if sctp lib can't immediately take the entire message. I see two options here:
a. Buffer at PeerConnection data channel level. The issue here is that this would change webrtc public API ([DataChannelObserver::OnBufferAmountChanged](https://cs.chromium.org/chromium/src/third_party/webrtc/api/data_channel_interface.h?l=93)), as well as the webrtc internal API that assumes that this call is atomic -[SendData()](https://cs.chromium.org/chromium/src/third_party/webrtc/media/sctp/sctp_transport_internal.h?l=104). I couldn't see in the spec if the WebRTC data channel expects the buffer size to decrease by entire message size, but I assume some dependencies rely on this behavior.
b. **preferred** Update the sctp library adapter ([sctp_transport.cc](https://cs.chromium.org/chromium/src/third_party/webrtc/media/sctp/sctp_transport.cc?q=sctp_transport.cc&l=503)) to buffer. This would keep all higher level interfaces the same and not break anything. I'm going to work on this fix and see if I can fix the issue.

@lgrahl - if we did go with option 1 above, while I agree that this would not be optimal throughput, would this necessarily be a regression on throughput? The library already assumes that this is atomic.

**Comment by lgrahl** [comment]
Agree that going with 2b) would be best. If you could use a reference implementation, there's the one in [Firefox](https://dxr.mozilla.org/mozilla-central/rev/95ad10e13fb1fe7a1b0e0fa10e31f1b5eb28cb62/netwerk/sctp/datachannel/DataChannel.cpp#2571) and in [RAWRTC](https://github.com/rawrtc/rawrtc-data-channel/blob/8444adc6f61b275c40653516588d61cb756ef4df/src/sctp_transport/transport.c#L469) (they look similar since the one in Firefox was ported from RAWRTC).

> would this necessarily be a regression on throughput?

In theory, if someone uses 256 KiB messages. I'd imagine, most still use 64 KiB. With the `RTCSctpTransport.maxMessageSize` interface now implemented, you'll have to expect more to jump on 256 KiB. But only testing (with an RTT way above 0) could tell. :slightly_smiling_face:

**Comment by shampson** [comment]
I think this issue can be closed with the fix. Thanks again for all the help debugging!

**Comment by alvestrand** [comment]
For info - I added that test when checking that we could actually send and receive the messages we were signalling as max message size. Nice to see that it uncovered a regression!
