### ISSUE TITLE
RTT calculation without SCTP_SACK_IMMEDIATELY

### ISSUE THREAD

**Issue by paniksystem** [sctplab/usrsctp#457]
Is the RTT reported by SCTP_STATUS accurate when not using the SCTP_SACK_IMMEDIATELY flag?
On localhost with 1ms real rtt:
- When sending 1 byte message every second, the RTT reported increases to reach approx. 200ms 
- When setting the SCTP_SACK_IMMEDIATELY flag, it stays at 1ms

**Comment by stewrtrs** [comment]
If you only send one packet then the RTT is going
to include the delayed ack time. A transport protocol
sending such a small amount will need to have that
built into its RTT since that it what sets timers and
if you send 1 packet say every 300ms you don’t want the
rxt timer going off due to a Delayed Ack coming from the
peer.

If you want a precise time, then you would either have to send
more data <or> add the SI flag.

R

> On Apr 27, 2020, at 8:27 AM, Gwenael FOURRE <notifications@github.com> wrote:
> 
> 
> Is the RTT reported by SCTP_STATUS accurate when not using the SCTP_SACK_IMMEDIATELY flag?
> On localhost with 1ms real rtt:
> 
> 	• When sending 1 byte message every second, the RTT reported increases to reach approx. 200ms
> 	• When setting the SCTP_SACK_IMMEDIATELY flag, it stays at 1ms
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or unsubscribe.
> 

------
Randall Stewart
rrs@netflix.com

**Comment by paniksystem** [comment]
sure, thanks for the confirmation
