### ISSUE TITLE
Transfer of large messages sometimes stalls

### ISSUE THREAD

**Issue by taylor-b** [sctplab/usrsctp#492]
When testing using [this WebRTC test page](https://webrtc.github.io/samples/src/content/datachannel/datatransfer/), sending 64MB using ordered mode, very frequently the transfer will stall at some point and resume a second or so later. Note that this page sends messages of size 256KB.

I was able to get a packet capture here: https://drive.google.com/file/d/1U2SxCRZTm9RtpLDjKwEiFSd08ohX8XAg/view?usp=sharing

The timing of packets may be a little confusing since both sides of the connection were recorded within the same tab; what you are seeing is the time at which packets were *received* by either side. 

Anyway, the issue happens at around packet 12092. The issue seems to be that a_rwnd is reduced from 49576 bytes in the SACK in packet 12062 down to 1 in the SACK in packet 12075, even though the cumulative TSN only increased by 2. I don't understand why it would be reduced so suddenly, or why a partial message wouldn't be delivered to the application via the receive callback to free up space.

A quarter of a second later, there's one more SACK, still with a_rwnd of 1, and one more DATA chunk in return. Another quarter second later this repeats, then repeats again, until eventually a SACK is sent with a_rwnd 130816 and everything resumes.

This is using a February 20 branch of usrsctp. I'll try to reproduce it with tip-of-tree, but it's difficult to reproduce at all, at least when I want it to.

@tuexen Are you aware of any existing issue, or issue fixed between February and today that would explain this? If it's any clue, the message size of 256KB seems highly related, the issue doesn't reproduce if I reduce it to 255KB.

**Comment by weinrank** [comment]
Hi @taylor-b ,

that sound very similar to a bug we've fixed last week.
See [here](https://github.com/sctplab/usrsctp/commit/8d7662e81b7192566eaa23a651210b7d07e009c1)

Can you try the most recent usrsctp version and report back?

**Comment by tuexen** [comment]
Hi @taylor-b 

here is what is happening:

There was a bug (fixed in https://github.com/sctplab/usrsctp/commit/8d7662e81b7192566eaa23a651210b7d07e009c1), which resulted in an much higher number of mbufs being used than necessary when handling incoming packets. Basically, we were not using mbuf clusters (although they were allocated), but long chains only consisting of mbufs.

Since you are using large message (which is fine), there is some buffering going on one the receiver side. To protect itself, a receiver announces a receive buffer of 1, if there are a substantial amount of mbufs being used. The above bug triggers this and you see this in the trace in various places. With the fix mentioned above, this should not occur anymore in this case.

However, such a case an happen (when dealing with a huge number of small packets).

What is happening and being described by you as "freezing", is not not really freeing. Is the sender honouring the peers receiver Window of 1 and only sending a single packets. This starts on the receiver side the delay ack timer and after 200ms the SACK is sent. This then triggers a SACK and so on. So you see delayed SACKs in frame 12093, 12095, 12097, and 12099.

What can be done to improve it? First of all, fix the memory allocation issue, which resulted in triggering this self protection when using large message. The delivery doesn't need to be fixed, since the protection should trigger when using small messages which can be delivered. What could be improved is to NOT delay SACKs when being in this situation. SACK are normally not delayed when there is loss or there are duplicated. So it would be consistent to do so. Will see if I can add such an improvement.

However, I would not expect this problem to occur anymore when using a version which contains https://github.com/sctplab/usrsctp/commit/8d7662e81b7192566eaa23a651210b7d07e009c1. Can you verify that?

**Comment by taylor-b** [comment]
So in short, the receiver runs low on memory because it's using mbuf chains instead of clusters, which are presumably more space efficient? Or is it because the clusters are allocated but not used?

I'll try to verify that 8d7662e fixes the issue, however as I mentioned it's quite temperamental. For whatever reason, I can reproduce it in an official Chrome build but not my local build; I'm assuming it's just very timing-dependent. Can you suggest any conditions that would make it more likely to occur?

**Comment by tuexen** [comment]
> So in short, the receiver runs low on memory because it's using mbuf chains instead of clusters, which are presumably more space efficient? Or is it because the clusters are allocated but not used?

It is because the stack monitors how much mbufs are used. If that is too high, the condition is triggered. In this case it is triggered, because you do some buffering (which is OK), but you just use mbufs for it (which is nit OK).

> 
> I'll try to verify that [8d7662e](https://github.com/sctplab/usrsctp/commit/8d7662e81b7192566eaa23a651210b7d07e009c1) fixes the issue, however as I mentioned it's quite temperamental. For whatever reason, I can reproduce it in an official Chrome build but not my local build; I'm assuming it's just very timing-dependent. Can you suggest any conditions that would make it more likely to occur?

Not really. It might be possible to trigger it deterministically if one would have packetdrill support for the usrsctp stack, but it only works with the kernel stack and there the problem does not occur. However, not delaying the SACK might be testable with packetdrill and the kernel stack.

**Comment by taylor-b** [comment]
Was able to reproduce it even with 8d7662e. Will try to get a log with SCTP_DEBUG enabled tomorrow; any specific categories I should be enabling?

**Comment by tuexen** [comment]
OK. Just use `DEBUG_ALL` and try to get a .pcapng file. What message sizes are you using? Ordered or unordered?

**Comment by taylor-b** [comment]
Still using 256KB messages, ordered.

Log: https://drive.google.com/file/d/1HI9RcsNt0ylurPSmLcAbJcvdRFjaRK-o/view?usp=sharing

pcap: https://drive.google.com/file/d/1r738wwRA0-Fpe-tErwDy4lzFQo06_bqt/view?usp=sharing

In this case it contains both incoming and outgoing packets. You can differentiate them from the frame header. Note that I cut the log off after the interesting bits because otherwise it was gigantic.

Gap occurs at packet 6546. I marked it in the text log with "GAP OCCURS HERE".

This appears to be a different problem than before. In this case some packets are lost.

At packet 6281, the chunk with TSN 290362123 is dropped.

It's retransmitted at packet 6379, though this retransmission is also not received.

Right afterwards there is another gap, indicating 290362127 was dropped. At packet 6489 it's retransmitted, at 6521 it's received.

Again there is a gap afterwards, between 290362181 and 290362188.

More SACKs are sent/received that indicate that 290362123 is still missing, until the receive window is exhausted. But then 290362123 is not retransmitted until a second later.

Is this just expected behavior when a retransmission is lost?

The reason the packets are getting dropped is actually because the socket send buffer was full. If we were returning `ENOBUFS` in this case, would usrsctp be smart enough to know that the chunk was not sent and needs to be retransmitted, even without the presence of the SACK?

**Comment by tuexen** [comment]
Looking at the tracefile from the receiver's perspective, I think everything is as expected. As soon as there are gaps in the TSN space, SACKs are sent for each received packet containing a DATA chunk and the gaps are reported. In the area you are describing, the TSNs `290362123`, `290362127`, and `290362181`- `290362188` are lost. I think we agree on this.

Looking at the tracefile from the sender's perspective, I also think everything is as expected. In frame `6274`, `6377`, and `6378` the TSN `290362123` is reported as missing. Therefore (after being reported lost for three times), a fast retransmission happens in frame `6379`. The same happens for TSN `290362127`. It is reported as missing in frame `6474`, `6487`, and `6488`.  The fast retransmission happens in frame `6489`.
The loss of TSNs `290362181`- `290362188` is reported once in frame `6546` by reporting the TSN `290362189` as received. Due to the flowcontrol no TSNs after TSN `290362189` are transmitted. So there is no chance that the lost TSNs `290362181`- `290362188` are recovered by fast retransmissions.
Therefore, a timer based retransmission has to resolve it. The minimum value has a default of 1 second as specified in RFC 4960. It could be changed via the API. Another way to improve the loss is to use an alternate loss recovery mechanism like RACK, which is currently being specified for TCP and @weinrank did some work for applying it to SCTP. However, his work is only done within a simulation environment right now.

> Is this just expected behavior when a retransmission is lost?

Yes, a lost fast retransmission will be recovered by a timer based retransmission. Also tail drops or drops almost at the tail have to be recovered by timer based retransmissions, because they can't receive 3 gap reports. It would make much sense to use RACK also for SCTP.

> 
> The reason the packets are getting dropped is actually because the socket send buffer was full. If we were returning `ENOBUFS` in this case, would usrsctp be smart enough to know that the chunk was not sent and needs to be retransmitted, even without the presence of the SACK?

The stack is smart enough to try to avoid the immediate sending of further packets. But the stack has no idea when the situation has resolved. So it just relies on the fast retransmission / timer based retransmission recovery.

The problem you are experiencing can happen if the local socket send buffer or the remote receive buffer size is smaller than the advertised receiver window received by the peer. Would it be possible to bump up these values to get them consistent with the values used that the SCTP layer? That way you would avoid these packet losses at least on your end, which definitely tend to be tail drops...

**Comment by taylor-b** [comment]
> The minimum value has a default of 1 second as specified in RFC 4960. It could be changed via the API.

I assume if the minimum is changed, the RTO will be determined based on when SACKs are received?

> Would it be possible to bump up these values to get them consistent with the values used that the SCTP layer? 

They're already pretty generous, but this particular sample page is trying to send as fast as possible, and is also very bursty, so it's basically the worst case scenario. 

It looks like, post-8d7662e, things are working as expected, so closing.

**Comment by tuexen** [comment]
> > The minimum value has a default of 1 second as specified in RFC 4960. It could be changed via the API.
> 
> I assume if the minimum is changed, the RTO will be determined based on when SACKs are received?
> 

The RTT is constantly measured and the RTO is computed as the smoothed RTT plus four times the smoothed RTT variance. Then the value is forced in the interval [RTO.min, RTO.max]. After a timeout, the value is doubled. That is also done for TCP, just a lot of TCP implementation have lowered RTO.min.
