### ISSUE TITLE
0.9.4.0 changed the interface and didn't bump the SONAME

### ISSUE THREAD

**Issue by yurivict** [sctplab/usrsctp#564]
Depending packages require to be patched now, for example https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=252581

Please always bump the shared library's soname when breaking API changes are made:
```
lib/libusrsctp.so.1
lib/libusrsctp.so.1.0.0
```
In this case 1 should be changed to 2.

**Comment by Neustradamus** [comment]
@yurivict: Thanks a lot for your issues, please read and comment here:
- https://github.com/sctplab/usrsctp/issues/561

**Comment by tehnick** [comment]
Yes, this is unfortunate situation.

@tuexen How about adding a tiny fix (just bumping of soversion/soname) and making of new git tag `0.9.4.1` for them?

**Comment by Neustradamus** [comment]
@tehnick: I think that 1.0.0 or 1.0.0.0 will be better, like Fedora 31/32/33/34 have already 1.0.0 versions: https://src.fedoraproject.org/rpms/usrsctp:
- Fedora 34 usrsctp-1.0.0-0.1.20201017gitf4925bd.fc34
- Fedora 33 usrsctp-1.0.0-0.1.20201017gitf4925bd.fc33
- Fedora 32 usrsctp-1.0.0-0.1.20201017gitf4925bd.fc32

From:
- https://github.com/sctplab/usrsctp/issues/561#issuecomment-753789438

cc: @xvitaly.

Note: The API has changed: https://github.com/sctplab/usrsctp/issues/561#issuecomment-757560433 + https://github.com/sctplab/usrsctp/issues/561#issuecomment-757578352 + https://github.com/sctplab/usrsctp/issues/318 + https://github.com/sctplab/usrsctp/issues/439

**Comment by tuexen** [comment]
> Yes, this is unfortunate situation.
> 
> @tuexen How about adding a tiny fix (just bumping of soversion/soname) and making of new git tag `0.9.4.1` for them?

Where is the soversion set in comparison to the version of the library? I guess for the autotools stuff, [this](https://github.com/sctplab/usrsctp/blob/master/configure.ac#L31) sets the version of the library, and [this](https://github.com/sctplab/usrsctp/blob/master/usrsctplib/Makefile.am#L79) sets the soversion.
@weinrank What are the corresponding entries for cmake?
@lgrahl What are the corresponding entries for meson?

We can bump the version 0.9.4.1 and to soversion to 2.

**Comment by tehnick** [comment]
> I guess for the autotools stuff, [this](https://github.com/sctplab/usrsctp/blob/23f2563c/configure.ac#L31) sets the version of the library, and [this](https://github.com/sctplab/usrsctp/blob/23f2563c/usrsctplib/Makefile.am#L79) sets the soversion.

I am not sure that this is correct assumption regarding soversion. As far as I see, package libusrsctp in Debian is built using autotools. (Just find `dh_auto_configure` in a [build log](https://buildd.debian.org/status/fetch.php?pkg=libusrsctp&arch=amd64&ver=0.9.3.0%2B20201102-2&stamp=1606701264&raw=0)) But resulting SONAME looks like:
```
$ objdump -p /usr/lib/x86_64-linux-gnu/libusrsctp.so.1.0.0 | grep SONAME
  SONAME               libusrsctp.so.1
```

So real soversion is autotools based builds is `1` now.

> What are the corresponding entries for cmake?

In cmake based builds library version and soversion are set by [one string](https://github.com/sctplab/usrsctp/blob/23f2563c/usrsctplib/CMakeLists.txt#L180):
```
set_target_properties(usrsctp PROPERTIES SOVERSION 1 VERSION 1.0.0)
```

I do not know a situation with Meson build system, because I have never worked with it, but [this](https://github.com/sctplab/usrsctp/blob/23f2563c/meson.build#L3) string looks very suspicious to me. Please test that shared library built by it has the same `SONAME   libusrsctp.so.1` as builds by other build systems.

> We can bump the version 0.9.4.1 and to soversion to 2.0.0.

I would recommend to use soversion `2` for version `0.9.4.1` instead, because current soversion is just `1`.

Just a side note for @jonassmedegaard , not related to library:
Do I understand correctly that we will be able to use only version `0.9.4.0` in Debian Bullseye? Because after bumping of library soname binary package should be renamed to `libusrsctp2` and this cannot be done now due to freeze of library transitions?

**Comment by xvitaly** [comment]
I will send a PR with fixes shortly.

**Comment by tehnick** [comment]
> I do not know a situation with Meson build system

Hey! I have looked at [packages](https://src.fedoraproject.org/rpms/usrsctp) in Fedora and I have found in [build log](https://kojipkgs.fedoraproject.org//packages/usrsctp/1.0.0/0.2.20210110gitf1de842.fc34/data/logs/x86_64/build.log) that they are built using `meson`. And as we see related compiler option  `-Wl,-soname,libusrsctp.so.1`, so everything is fine.

**Comment by xvitaly** [comment]
Meson does not support X.Y.Z.N versions:

```
../meson.build:188:4: ERROR: Invalid Shared library version "0.9.4.1". Must be of the form X.Y.Z where all three are numbers. Y and Z are optional.
```

**Comment by xvitaly** [comment]
Introduced a separate API/ABI version fields for shared library version:

Meson:
```
# Shared library API and ABI versions
sharedlib_version = '0.9.4'
sharedlib_soversion = '2'
```

Cmake:

```
# Shared library API and ABI versions
set(SHAREDLIB_VERSION "0.9.4")
set(SHAREDLIB_SOVERSION "2")
```

Will try to do the same for the automake.

**Comment by xvitaly** [comment]
Results:

```
lrwxrwxrwx. 1 vitaly vitaly      15 Jan 13 13:07 libusrsctp.so -> libusrsctp.so.2
-rwxrwxr-x. 1 vitaly vitaly 1801360 Jan 13 13:07 libusrsctp.so.0.9.4
lrwxrwxrwx. 1 vitaly vitaly      19 Jan 13 13:07 libusrsctp.so.2 -> libusrsctp.so.0.9.4
```

```
$ objdump -p libusrsctp.so.0.9.4 | grep SONAME
  SONAME               libusrsctp.so.2
```

Now LGTM.

**Comment by xvitaly** [comment]
But the legacy automake build system cannot use the similar scheme. It always producea a symbolic link with full soversion number.

```
lrwxrwxrwx. 1 vitaly vitaly      19 Jan 13 13:40 libusrsctp.so -> libusrsctp.so.2.0.0
lrwxrwxrwx. 1 vitaly vitaly      19 Jan 13 13:40 libusrsctp.so.2 -> libusrsctp.so.2.0.0
-rwxr-xr-x. 1 vitaly vitaly 1798720 Jan 13 13:40 libusrsctp.so.2.0.0
```

**Comment by xvitaly** [comment]
I think it will be better to use the full SOVERSION to be unified with all supported build systems. I will update my PR shortly.

**Comment by jonassmedegaard** [comment]
> > I guess for the autotools stuff, [this](https://github.com/sctplab/usrsctp/blob/23f2563c/configure.ac#L31) sets the version of the library, and [this](https://github.com/sctplab/usrsctp/blob/23f2563c/usrsctplib/Makefile.am#L79) sets the soversion.

Almost correct.

SONAME is *not* the value defined in the [Makefile](https://github.com/sctplab/usrsctp/blob/23f2563c/usrsctplib/Makefile.am#L79) but is computed from those 3 components.

Probably best documentation of libtool versioning (better than official documentation) is this: https://autotools.io/libtool/version.html

> I am not sure that this is correct assumption regarding soversion. As far as I see, package libusrsctp in Debian is built using autotools. (Just find `dh_auto_configure` in a [build log](https://buildd.debian.org/status/fetch.php?pkg=libusrsctp&arch=amd64&ver=0.9.3.0%2B20201102-2&stamp=1606701264&raw=0)) But resulting SONAME looks like:
> 
> ```
> $ objdump -p /usr/lib/x86_64-linux-gnu/libusrsctp.so.1.0.0 | grep SONAME
>   SONAME               libusrsctp.so.1
> ```
> 
> So real soversion is autotools based builds is `1` now.

Correct.

> > We can bump the version 0.9.4.1 and to soversion to 2.0.0.
> 
> I would recommend to use soversion `2` for version `0.9.4.1` instead, because current soversion is just `1`.

I would recommend to read the libtool versioning documentation referenced above before deciding which should be the nex SONAME.


> Just a side note for @jonassmedegaard , not related to library:
> Do I understand correctly that we will be able to use only version `0.9.4.0` in Debian Bullseye? Because after bumping of library soname binary package should be renamed to `libusrsctp2` and this cannot be done now due to freeze of library transitions?

Correct: Yesterday was the deadline for introducing major library changes (and "introducing" involves a screening by the Debian ftpmaster team which can take days or weeks, so even if uploaded yesterday it was unlikely to make it in time).

That said, the damage is already done: the breaking change tracked in this issue was introduced 5 months ago and is included in Debian.
Therefore the ideal, as I see it, would be that this project as soon as possible issue a release with SONAME bumped, and that I try make an exception to have it included in Debian despite having passed the deadline (there is currently only one package in Debian depending on it, which helps making such exception).

**Comment by xvitaly** [comment]
@tehnick @jonassmedegaard Please check PR #565. It should fix all of these issues.

**Comment by jonassmedegaard** [comment]
otherwise - if Debian won't accept an exception to sneak in a new major release of libusrsctp, then it simply means what was known already: That SONAME 1 is an unstable SONAME that can mean multiple things, because it stayed the same across multiple years with (unfortunately) at least one breakage.
