### ISSUE TITLE
Working with native SCTP

### ISSUE THREAD

**Issue by gedOHub** [sctplab/usrsctp#76]
Hello,
How to work directly with SCTP protocol, but not with UDP encapsulation?

**Comment by gedOHub** [comment]
Haven't saw this: 

> If UDP encapsulation is not necessary, the UDP port has to be set to 0.

**Comment by gedOHub** [comment]
Is there any example program working directly with SCTP?

**Comment by tuexen** [comment]
Sure:
* `programs/client`
* `programs/daytime_server`
* `programs/discard_server`
* `programs/echo_server`
* `programs/http_client`
* `programs/tsctp`

**Comment by weinrank** [comment]
@gedOHub which OS are you using?

To make sure: You are running the samples as root when using native SCTP?

**Comment by gedOHub** [comment]
Yes, running as administrator (windows). Still trying to figure out how lib works :)

**Comment by gedOHub** [comment]
For example, why echo_server without parameters opens UDP 9899 port? Uses UDP encapsulation?

**Comment by weinrank** [comment]
Because he is told to do so! 😀 
See [echo_server.c](https://github.com/sctplab/usrsctp/blob/master/programs/echo_server.c#L159-L163) and [usrsctp_init()](https://github.com/sctplab/usrsctp/blob/master/Manual.md#usrsctp_init)

Have you tried to use the `http_client`? It's a handy example to get familiar with the usrsctp usage on client side. 

To disable the verbose debug output, simply uncomment the `usrsctp_sysctl_set_sctp_debug_on(SCTP_DEBUG_ALL);` line [here](https://github.com/sctplab/usrsctp/blob/master/programs/http_client.c#L108)

You can test it with and without UDP-encapsulation against a small test system we are running
`./http_client 212.201.121.100 80 0 9899 9899` with udp encaps
`./http_client 212.201.121.100 80` native/raw sctp - run as admin
Running native SCTP may fail because of middleboxes and NATs.

Generally it is recommended that you don't run the server and a client on the same machine to avoid problems. Especially for debugging with Wireshark it's highly recommended to use two machines / VMs.

**Comment by gedOHub** [comment]
I need to run native SCTP for experment. So, to run native SCTP I need to usrsctp_init with first argument 0?

**Comment by weinrank** [comment]
No, it is not required to set the first argument 0.
Setting the first argument simply adds the UDP-encpas functionality - the raw SCTP remains active.
For RAW SCTP you have to run SCTP as an Administrator level.

**Comment by gedOHub** [comment]
After deep examination of http_client and your comments now it is clear how lib works. Thank you!!
